instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from .views import (
    HomeView,
    logout_view,
    MyLoginView,
    ContactUsFormView,
    # CustomLogoutView,
    RegisterView,
)

from django.conf import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path("",HomeView.as_view(), name="home"),
    path("login",MyLoginView.as_view(), name="login"),
    path("registro", RegisterView.as_view(), name='registro'),
    path("logout",logout_view, name="logout"),
    path("contact", ContactUsFormView.as_view(), name='contacto'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls')),
    ]

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    PostCreateView,
    PostListView,
    PostDetailView,
    post_like,
    post_like_ajax,
)
app_name = "posts"

urlpatterns = [
    path("postlist",PostListView.as_view(), name="post_list"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path("<pk>", PostDetailView.as_view(), name="post_detail"),    
    path("like/<pk>", post_like, name="post_like"),
    path("like-ajax/<pk>", post_like_ajax, name="post_like_ajax"),
    
]

profiles/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    ProfileListView,
    ProfileDetailView,
    ProfileUpdateView,
    # BlogCreateView,
    # BlogDeteteView,
)
app_name = "profiles"

urlpatterns = [
    path("list",ProfileListView.as_view(), name="profile_list"),
    path("<pk>", ProfileDetailView.as_view(), name="profile_detail"),
    # path("nuevo/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<pk>", ProfileUpdateView.as_view(), name="profile_update"),
    # path("borrar/<pk>", BlogDeteteView.as_view(), name="blog_delete"),
    
]

instagram/forms/comment_create_form.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from posts.models import Comments

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = [ 
            "text",
            ]

instagram/forms/contact_form.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy


class ContactForm(forms.Form):
    
    nombre = forms.CharField(
        label=_("Nombre"),
        max_length=100
    )
    email = forms.EmailField(
        label=_("Correo electronico"),
    )
    comentario = forms.CharField(
        label=_("Comentario"),
        max_length= 300,
        widget=forms.Textarea,
    )
    def clean_comentario(self):
        comentario = self.cleaned_data["comentario"]
        if len(comentario) < 5:
            raise forms.ValidationError(_("El comentario debe tener al menos 5 caracteres"))
        return comentario
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        if len(nombre) < 5:
            raise forms.ValidationError(_("El nombre debe tener al menos 5 caracteres"))
        return nombre
    
    

instagram/forms/post_create_form.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from posts.models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [   
            "image",
            "description",
            ]

# class LoginForm(forms.Form):
#     username = forms.CharField(
#         label=_("Nombre de usuario"),
#         max_length=140,
#         required=True
#     )
#     password = forms.CharField(
#         widget=forms.PasswordInput(),
#         label=_("Contraseña")
#     ) 



# # def registro_view(request):
#     if request.POST:
#         formulario = UserRegisterForm(request.POST)
#         if formulario.is_valid():
#             username = formulario.cleaned_data["username"]
#             first_name = formulario.cleaned_data["first_name"]
#             last_name = formulario.cleaned_data["Last_name"]
#             email = formulario.cleaned_data["email"]
#             password1 = formulario.cleaned_data["password1"]
#             password2 = formulario.cleaned_data["password2"]
#             user =User.objects.create_user(username,email,password2)
#             if user: 
#                 user.first_name = first_name
#                 user.last_name = last_name
#                 user.password1 = password1
#                 user.save()
                
#             context = {
#                 "msg" : _("Usuario creado correctamente"),
                
#             }
#             return render(request,'general/registro.html', context)
        
#         else:
#             context = {
#                 "form" : formulario,
#             }
#             return render(request,'general/registro.html', context)
#     else:
#         formulario = UserRegisterForm()
#         context = {
#             "form" : formulario
#             }
#         return render(request,'general/registro.html', context)

profiles/forms.py
from django import forms

class ProfileFollow(forms.Form):
    profile_pk = forms.IntegerField(label="Identificador de usuario",widget=forms.HiddenInput())

instagram/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView,FormView
from django.shortcuts import render,redirect
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login,logout
from django.core.mail import send_mail
from .forms.contact_form import ContactForm
from .forms.user_forms import UserRegisterForm #,registro_view
from django.utils.translation import gettext as _
from django.contrib import messages
from django.contrib.auth.models import User
from profiles.models import UserProfile
from posts.models import Post


# Create your views here.
# @method_decorator(login_required,name='dispatch')
class HomeView(TemplateView):
    template_name = 'general/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["perfiles"] = UserProfile.objects.all()
        if self.request.user.is_authenticated:
            context["last_posts"] = Post.objects.all().exclude(user_id=self.request.user.pk).order_by('-created_at')[:5]
        else: 
            context["last_posts"] = Post.objects.all().order_by('-created_at')[:5]
        return context

    
class RegisterView(CreateView):
    model=User
    form_class = UserRegisterForm
    template_name = 'general/registro.html'

    def form_valid(self, form):
        form.instance.created_by= self.request.user
        messages.add_message(self.request, messages.SUCCESS,_('Usuario Registrado correctamente!'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('login')

class MyLoginView(LoginView):
    template_name = 'general/login.html'  # Nombre de tu plantilla HTML
    redirect_authenticated_user = True  # Redirige a usuarios ya autenticados
    success_url = reverse_lazy('home')  # URL a la que redirigir después del inicio de sesión exitoso
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(self.request,messages.SUCCESS,_('Usuario Logueado correctamente!'))
        return response


    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['user'] = self.request.user
    #     return context

# @login_required
def logout_view(request):
    logout(request)
    messages.add_message(request, messages.INFO,_('Sesion cerrada correctamente'))
    return redirect(reverse_lazy("home"))


class ContactUsFormView(FormView):
    template_name = 'general/contact.html'
    form_class = ContactForm
    
    def get_success_url(self):
        return reverse_lazy('home')

    def form_valid(self, form):
        nombre = form.cleaned_data["nombre"]
        email = form.cleaned_data["email"]
        comentario = form.cleaned_data["comentario"]
        message_content = (f'{nombre} con email {email} ha escrito lo siguiente: {comentario}')
        success = send_mail(
            ("formulario de contacto de mi web de Instaconquer"),
            message_content,
            "info@angamadev.com",
            ["angamadev@gmail.com"],
            fail_silently=False,
        )
        messages.add_message(self.request,messages.SUCCESS, "Mensaje enviado correctamente")
        return super().form_valid(form)
    
    
class CustomLogoutView(LogoutView):
    next_page = 'login'  # Página a la que redirigir después de cerrar sesión
    success_url = reverse_lazy('home')  # URL a la que redirigir después del inicio de sesión exitoso

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,TemplateView,FormView
from .models import Post,Comments
from django.contrib import messages
from instagram.forms.post_create_form import PostCreateForm
from instagram.forms.comment_create_form import CommentCreateForm

from django.utils.translation import gettext_lazy as _lazy
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect,JsonResponse


# Create your views here.
@method_decorator(login_required,name='dispatch')
class PostCreateView(CreateView):
    model=Post
    form_class = PostCreateForm
    template_name = 'posts/post_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.add_message(self.request, messages.SUCCESS,_('Post creado correctamente!'))
        return super(PostCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('home')
    
@method_decorator(login_required,name='dispatch')
class PostListView(TemplateView):
    template_name = 'posts/post_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["publicaciones"] = Post.objects.all()
        return context
    
@method_decorator(login_required,name='dispatch')
class PostDetailView(DetailView,FormView):
    
    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = "post"
    form_class = CommentCreateForm
    
    def form_valid(self, form):
        form.instance.post = self.get_object()
        form.instance.user = self.request.user
        form.save()  # Agrego esta línea para guardar el comentario
        messages.add_message(self.request, messages.SUCCESS,_('Comentario añadido correctamente!'))
        return super(PostDetailView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse("posts:post_detail", args=[self.get_object().pk])

@login_required
def post_like(request,pk):
    post = Post.objects.get(pk=pk)
    if request.user in post.likes.all():
        messages.add_message(request, messages.INFO, "Ya no te gusta esta publicacion.")
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        messages.add_message(request, messages.INFO, "Me gusta la publicacion")
    
    return HttpResponseRedirect(reverse("posts:post_detail", args=[pk]))
    
@login_required
def post_like_ajax(request,pk):
    post = Post.objects.get(pk=pk)
    
    if request.user in post.likes.all():
        post.likes.remove(request.user)
        return  JsonResponse(
            {
                'message':'Ya no te gusta esta publicacion.',
                'liked': False,
                'nLikes': post.likes.all().count()
            }
        )
    else:
        post.likes.add(request.user)
        return  JsonResponse(
            {
                'message':'Me gusta la publicacion.',
                'liked': True,
                'nLikes': post.likes.all().count()
            }
        )

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView, ListView,FormView
from .models import UserProfile,Follow
from posts.models import Post
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import ProfileFollow
import ipdb

# Create your views here.
@method_decorator(login_required,name='dispatch')
class ProfileListView(ListView):
    model = UserProfile
    template_name = 'profiles/profile_list.html'
    context_object_name = "profiles"
        
    def get_queryset(self):
        return UserProfile.objects.all().exclude(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class ProfileDetailView(DetailView, FormView):
    model = UserProfile
    template_name = "profiles/profile_detail.html"
    context_object_name = "userprofile"
    form_class = ProfileFollow

    def get_initial(self):
        self.initial['profile_pk'] =  self.get_object().pk
        return super().get_initial()

    def form_valid(self, form):
        profile_pk = form.cleaned_data.get('profile_pk')
        # action = form.cleaned_data.get('action')
        following = UserProfile.objects.get(pk=profile_pk)

        ## Compruebo si lo sigo o no en mi Queryset
        # Si Si lo sigo lo borro de mis seguidores y muestro mensaje
        if Follow.objects.filter(
            follower=self.request.user.profile,
            following=following
            ).count(): 
            Follow.objects.filter(
                follower=self.request.user.profile,
                following=following
                ).delete()
            messages.add_message(
                self.request, 
                messages.SUCCESS, 
                f"Se ha dejado de seguir a {following.user.username}"
                )
        # En cambio si NO lo sigo lo añado a mis seguidores y muestro mensaje
        else:
            Follow.objects.get_or_create(
                follower=self.request.user.profile,
                following=following
                )
            messages.add_message(
                self.request,
                messages.SUCCESS, 
                f"Se empieza a seguir a {following.user.username}"
                )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("profiles:profile_detail", args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        publicaciones = Post.objects.all() 
        context["publicaciones"] = publicaciones

        # Comprobamos si seguimos al usuario
        following = Follow.objects.filter(
            follower=self.request.user.profile, 
            following=self.get_object()
            ).exists()
        context['following'] = following
        return context
    
@method_decorator(login_required,name='dispatch')
class ProfileUpdateView(UpdateView):
    model = UserProfile
    fields = [
        "user",
        "bio",
        "profile_picture",
        "birth_date",        
        ]
    template_name = 'profiles/profile_update.html'
    context_object_name = "profile"
    
    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS,'¡Perfil editado correctamente!')
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse("profiles:profile_detail",args=[self.object.pk])
    
    def dispatch(self, request, *args, **kwargs):
        user_profile = self.get_object()
        if user_profile.user != self.request.user:
            return HttpResponseRedirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

instagram/templates/_includes/_footer_principal.html
<div class="container">
    {% load i18n %}
    <hr>
    <p>  {{ current_year }}{% trans " - Conquer Blocks, Todos los derechos reservados " %}</p>
</div>

instagram/templates/_includes/_languajes.html
{% load i18n %}
{% load crispy_forms_tags %}

<!-- Contenido del select del Lenguaje -->
<div class="col-md-2 text-end">
    <form action="{% url 'set_language' %}" method="post">
        <div class="col"> 
            {% csrf_token %}
            {{ form.language|crispy }}
            <select class="form-select" name="language">
                {% get_current_language as LANGUAGE_CODE %}
                {% for lang_code, lang_name in LANGUAGES %}
                    <option value="{{ lang_code }}" {% if LANGUAGE_CODE == lang_code %}selected{% endif %}>{{ lang_name }} ({{ lang_code }})</option>
                {% endfor %}
            </select>
        </div>
        <div class="col">
            <input type="hidden" name="next" value="{{ request.path }}">
            <button class="btn btn-warning" type="submit">{% trans "Cambiar Idioma" %}</button>
        </div>
    </form>
</div>

instagram/templates/_includes/_lasts_posts.html
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load i18n %}

<div class="d-flex ">

    {% for post in last_posts %}

            <article id="{{ post.pk }}" class="bg-secondary col sm-3 m-3 p-3 rounded-5">
                <p> 
                    Publicado por {{ post.user.first_name }} el {{ post.created_at}} - {{ userprofile.followers.count }} Me gustas
                </p> 
                <picture class="d-flex justify-content-center">
                    <img src="{% thumbnail  post.image 'small'  %}" class="rounded-3">
                </picture>
                <p class="mt-3"> 
                    Comentario: {{ post.description|truncatechars:45 }} 
                </p>
                {% if request.user.is_authenticated %}
                    <div class="d-flex justify-content-center">
                        <button class="btn btn-info ">
                            <a href={% url 'posts:post_detail' post.pk %}>{% trans 'Ver Post' %}</a>
                        </button>
                    </div>
                    <div class="d-flex justify-content-center">
                        <p class="text-center mt-3">
                            <a href="{% url 'posts:post_like_ajax' post.pk %}" class="likeButton">
                                <span>
                                    {{ post.likes.count }}
                                </span>
                                {% if request.user in post.likes.all %}
                                    <i class="bi bi-heart-fill"></i>
                                {% else %}
                                    <i class="bi bi-heart"></i>
                                {% endif %}
                            </a>
                            <i class="bi bi-chat"></i> <span>{{ post.comments.all.count }}</span>
                        </p>
                    </div>
                {% endif %}
            </article>
            <hr>
    {% endfor %} 
</div>

instagram/templates/_includes/_menu_principal.html
{% load i18n %}
{% load crispy_forms_tags %}

<ul>
    <li><a href={% url 'home' %}>{% trans "Inicio" %} </a></li>
    <li><a href={% url 'contacto' %}>{% trans "Contacto"%}</a></li>

        {% if request.user.is_authenticated %}
            <li><a href={% url "profiles:profile_list" %}>{% trans "Perfiles" %}</a></li>
            <li><a href={% url "profiles:profile_detail" request.user.profile.pk  %}>{% trans "Ver mi Perfil" %}</a></li>
            <li><a href={% url "posts:post_create" %}>{% trans "Nueva Publicacion" %}</a></li>
            <li><a href={% url "logout" %}>{% trans "Cerrar Sesion" %}</a></li>
            <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
            

            </form>
        {% else %}
                <li><a href={% url "registro" %}>{% trans "Registro" %}</a></li>
                <li><a href={% url "login" %}>{% trans "Login" %}</a></li>
        
        {% endif %}
    </div>
</div>
{% include "_includes/_messages.html" %}
<hr>

instagram/templates/_includes/_messages.html
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load i18n %}
<div class="container">
    <div class="row mt-2 mb-2">
        <div class="col-sm">
            {% for message in messages %}
                <div class="alert
                    {% if message.tags %}
                        {% if message.tags == 'error' %}
                            alert-danger
                        {% else %}
                            alert-{{ message.tags }}
                        {% endif %}
                    {% else %}
                        alert-info
                    {% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

instagram/templates/_includes/_post_detail.html
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load i18n %}
{% load static %}

<article id="{{ post.pk }}">
    <div class="container mt-5 mb-5">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="d-flex justify-content-between p-2 px-3">
                        <div class="d-flex flex-row align-items-center"> 
                            <img src="{% thumbnail  post.user.profile.profile_picture 'small'  %}" width="50" class="rounded-circle"></img>
                            <span class="font-weight-bold">{{ post.user.first_name }}</span>
                        </div>
                        <div class="d-flex flex-row mt-1 ellipsis"> 
                            <p class="mr-2">Publicado el {{ post.created_at}}</p> 
                            <i class="fa fa-ellipsis-h"></i> 
                        </div>
                    </div> 
                    <img src="{% thumbnail  post.image 'medium'  %}" class="img-fluid"></img>
                    <div class="p-2">
                        <p class="text-justify">
                            {{ post.description }}  
                        </p>
                        <div>
                            <p class="text-center mt-3">
                                <a href="{% url 'posts:post_like_ajax' post.pk %}" class="likeButton">
                                    <span>{{ post.likes.all.count }}</span>
                                    {% if request.user in post.likes.all %}
                                        <i class="bi bi-heart-fill"></i>
                                    {% else %}
                                        <i class="bi bi-heart"></i> 
                                    {% endif %}
                                </a>
                                <i class="bi bi-chat"></i> <span>{{ post.comments.all.count }}</span>
                            </p>
                        </div>
                        <div class="Comentarios">
                            {% if post.comments.all.count > 0 %}
                                <details>
                                    <summary>Ver Comentarios:</summary>
                                    <p></p>
                                    {% for comment in post.comments.all  %}
                                        <article class="bg-primary">
                                            <header>
                                                <strong>Autor:</strong> {{ comment.user }} <strong>Creado el:</strong> {{ comment.created_at }}
                                            </header>
                                            <div>
                                                <p>{{ comment.text }}</p>
                                            </div>
                                        </article>
                                    {% endfor %}
                                </details>
                            {% else %}
                                <p class="bg-info">No hay comentarios.</p>
                            {% endif %}
                            <details>
                                <summary>Crear Nuevo Comentario:</summary>
                                <p></p>
                                <div>
                                    {% if post.user != request.user %}
                                        <form action="" method="post">
                                            {% csrf_token %}
                                            {{ form.text|as_crispy_field }}
                                            <button class="btn btn-info" type="submit">Comentar</button>
                                        </form>        
                                    {% endif %}
                                </div>
                            </details>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>          
</article>

instagram/templates/_includes/_posts.html
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load i18n %}

<article id="{{ post.pk }}">
    <div class="container mt-5 mb-5">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="d-flex justify-content-between p-2 px-3">
                        <div class="d-flex flex-row align-items-center"> 
                            <img src="{% thumbnail  post.user.profile.profile_picture 'small'  %}" width="50" class="rounded-circle">
                            <span class="font-weight-bold">{{ userprofile.user.first_name }}</span>
                        </div>
                        <div class="d-flex flex-row mt-1 ellipsis"> 
                            <small class="mr-2">Publicado el {{ post.created_at}}</small> 
                            <i class="fa fa-ellipsis-h"></i> 
                        </div>
                    </div> 
                    <img src="{% thumbnail  post.image 'medium'  %}" class="img-fluid">
                    <div class="p-2">
                        <p class="text-justify">{{ post.description }}  </p>
                    </div>
                    <div>
                        <p class="text-center mt-3">
                            {% if request.user.pk == userprofile.user.pk %}
                                <i class="bi bi-chat"></i> <span>{{ post.comments.all.count }}</span>
                            {% else  %}
                                <a href="{% url 'posts:post_like_ajax' post.pk %}" class="likeButton">
                                    <span >{{ post.likes.count }}</span>
                                    {% if request.user in post.likes.all %}
                                        <i class="bi bi-heart-fill"></i>
                                    {% else %}
                                        <i class="bi bi-heart"></i>
                                    {% endif %}
                                </a>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>          
</article>

instagram/templates/_includes/_profiles.html
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load i18n %}

<div class="d-flex px-3">

    {% for perfil in profiles %}
        <article id="{{ perfil.pk }}" class="col p-3 m-3 align-content-stretch rounded-5 text-center bg-secondary">
            <h3 class=""> {{ perfil.user }} </h3>
            <picture>
                <img src="{% thumbnail  perfil.profile_picture 'small'  %}" class="rounded-3">
            </picture>
            <p class="mt-3 rounded-5 bg-white">
                <a href={% url 'profiles:profile_detail' perfil.pk %}>{% trans 'Ver el Perfil' %}  </a>
            </p>
            <p class="mt-3 rounded-5 bg-white">
                {% trans 'Seguidores: ' %} {{ perfil.followers.count }}  
            </p>
        </article> 
    {% endfor %} 

</div> 