instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from .views import (
    HomeView,
    logout_view,
    MyLoginView,
    ContactUsFormView,
    # CustomLogoutView,
    RegisterView,
)

from django.conf import settings

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path("",HomeView.as_view(), name="home"),
    path("login",MyLoginView.as_view(), name="login"),
    path("registro", RegisterView.as_view(), name='registro'),
    path("logout",logout_view, name="logout"),
    path("contact", ContactUsFormView.as_view(), name='contacto'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('rosetta/', include('rosetta.urls')),
    ]

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    PostCreateView,
    PostListView,
    PostDetailView,
    post_like,
    post_like_ajax,
)
app_name = "posts"

urlpatterns = [
    path("postlist",PostListView.as_view(), name="post_list"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path("<pk>", PostDetailView.as_view(), name="post_detail"),    
    path("like/<pk>", post_like, name="post_like"),
    path("like-ajax/<pk>", post_like_ajax, name="post_like_ajax"),
    
]

profiles/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    ProfileListView,
    ProfileDetailView,
    ProfileUpdateView,
    # BlogCreateView,
    # BlogDeteteView,
)
app_name = "profiles"

urlpatterns = [
    path("list",ProfileListView.as_view(), name="profile_list"),
    path("<pk>", ProfileDetailView.as_view(), name="profile_detail"),
    # path("nuevo/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<pk>", ProfileUpdateView.as_view(), name="profile_update"),
    # path("borrar/<pk>", BlogDeteteView.as_view(), name="blog_delete"),
    
]

instagram/models/user_model_form.py
from django import forms
from django.contrib.auth.password_validation import validate_password



class UserForm(forms.Form):
    username = forms.CharField(
        label="Nombre de usuario",
        max_length=140,
    )
    first_name = forms.CharField(
        label="Nombre",
        max_length=140,
    )
    last_name = forms.CharField(
        label="Apellidos",
        max_length=140,
    )
    email = forms.EmailField(
        label="Email",
        max_length=140,
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(),
        label="Contraseña",
        required=True,
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label="Repite tu contraseña",
        required=True,
    )
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        
        if password1 != password2 and password1 != "":
            raise forms.ValidationError("Las contraseñas no coinciden")
        
        if password2 != "":
            validate_password(password2)
        
        return password2
    
    def clean_nombre(self):
        first_name = self.cleaned_data["first_name"]
        if len(first_name) < 5:
            raise forms.ValidationError("El nombre debe tener al menos 5 caracteres")
        return first_name

instagram/forms/comment_create_form.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from posts.models import Comments

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = [ 
            "text",
            ]

instagram/forms/contact_form.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy


class ContactForm(forms.Form):
    
    nombre = forms.CharField(
        label=_("Nombre"),
        max_length=100
    )
    email = forms.EmailField(
        label=_("Correo electronico"),
    )
    comentario = forms.CharField(
        label=_("Comentario"),
        max_length= 300,
        widget=forms.Textarea,
    )
    def clean_comentario(self):
        comentario = self.cleaned_data["comentario"]
        if len(comentario) < 5:
            raise forms.ValidationError(_("El comentario debe tener al menos 5 caracteres"))
        return comentario
    
    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        if len(nombre) < 5:
            raise forms.ValidationError(_("El nombre debe tener al menos 5 caracteres"))
        return nombre
    
    

instagram/forms/post_create_form.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from posts.models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [   
            "image",
            "description",
            ]

# class LoginForm(forms.Form):
#     username = forms.CharField(
#         label=_("Nombre de usuario"),
#         max_length=140,
#         required=True
#     )
#     password = forms.CharField(
#         widget=forms.PasswordInput(),
#         label=_("Contraseña")
#     ) 



# # def registro_view(request):
#     if request.POST:
#         formulario = UserRegisterForm(request.POST)
#         if formulario.is_valid():
#             username = formulario.cleaned_data["username"]
#             first_name = formulario.cleaned_data["first_name"]
#             last_name = formulario.cleaned_data["Last_name"]
#             email = formulario.cleaned_data["email"]
#             password1 = formulario.cleaned_data["password1"]
#             password2 = formulario.cleaned_data["password2"]
#             user =User.objects.create_user(username,email,password2)
#             if user: 
#                 user.first_name = first_name
#                 user.last_name = last_name
#                 user.password1 = password1
#                 user.save()
                
#             context = {
#                 "msg" : _("Usuario creado correctamente"),
                
#             }
#             return render(request,'general/registro.html', context)
        
#         else:
#             context = {
#                 "form" : formulario,
#             }
#             return render(request,'general/registro.html', context)
#     else:
#         formulario = UserRegisterForm()
#         context = {
#             "form" : formulario
#             }
#         return render(request,'general/registro.html', context)

instagram/forms/user_forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy as _lazy
from django.shortcuts import render,redirect
from django.contrib.auth.models import User

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = [   
            "username",
            "first_name",
            "email",
            "password",
            ]
    def save(self):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data["password"])
        user.save()

        from profiles.models import UserProfile
        UserProfile.objects.create(user=user)

        return user

# class LoginForm(forms.Form):
#     username = forms.CharField(
#         label=_("Nombre de usuario"),
#         max_length=140,
#         required=True
#     )
#     password = forms.CharField(
#         widget=forms.PasswordInput(),
#         label=_("Contraseña")
#     ) 



# # def registro_view(request):
#     if request.POST:
#         formulario = UserRegisterForm(request.POST)
#         if formulario.is_valid():
#             username = formulario.cleaned_data["username"]
#             first_name = formulario.cleaned_data["first_name"]
#             last_name = formulario.cleaned_data["Last_name"]
#             email = formulario.cleaned_data["email"]
#             password1 = formulario.cleaned_data["password1"]
#             password2 = formulario.cleaned_data["password2"]
#             user =User.objects.create_user(username,email,password2)
#             if user: 
#                 user.first_name = first_name
#                 user.last_name = last_name
#                 user.password1 = password1
#                 user.save()
                
#             context = {
#                 "msg" : _("Usuario creado correctamente"),
                
#             }
#             return render(request,'general/registro.html', context)
        
#         else:
#             context = {
#                 "form" : formulario,
#             }
#             return render(request,'general/registro.html', context)
#     else:
#         formulario = UserRegisterForm()
#         context = {
#             "form" : formulario
#             }
#         return render(request,'general/registro.html', context)

profiles/forms.py
from django import forms

class ProfileFollow(forms.Form):
    profile_pk = forms.IntegerField(label="Identificador de usuario",widget=forms.HiddenInput())

instagram/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView,FormView
from django.shortcuts import render,redirect
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login,logout
from django.core.mail import send_mail
from .forms.contact_form import ContactForm
from .forms.user_forms import UserRegisterForm #,registro_view
from django.utils.translation import gettext as _
from django.contrib import messages
from django.contrib.auth.models import User
from profiles.models import UserProfile
from posts.models import Post


# Create your views here.
# @method_decorator(login_required,name='dispatch')
class HomeView(TemplateView):
    template_name = 'general/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["perfiles"] = UserProfile.objects.all()
        if self.request.user.is_authenticated:
            context["last_posts"] = Post.objects.all().exclude(user_id=self.request.user.pk).order_by('-created_at')[:5]
        else: 
            context["last_posts"] = Post.objects.all().order_by('-created_at')[:5]
        return context

    
class RegisterView(CreateView):
    model=User
    form_class = UserRegisterForm
    template_name = 'general/registro.html'

    def form_valid(self, form):
        form.instance.created_by= self.request.user
        messages.add_message(self.request, messages.SUCCESS,_('Usuario Registrado correctamente!'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('login')

class MyLoginView(LoginView):
    template_name = 'general/login.html'  # Nombre de tu plantilla HTML
    redirect_authenticated_user = True  # Redirige a usuarios ya autenticados
    success_url = reverse_lazy('home')  # URL a la que redirigir después del inicio de sesión exitoso
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(self.request,messages.SUCCESS,_('Usuario Logueado correctamente!'))
        return response


    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['user'] = self.request.user
    #     return context

# @login_required
def logout_view(request):
    logout(request)
    messages.add_message(request, messages.INFO,_('Sesion cerrada correctamente'))
    return redirect(reverse_lazy("home"))


class ContactUsFormView(FormView):
    template_name = 'general/contact.html'
    form_class = ContactForm
    
    def get_success_url(self):
        return reverse_lazy('home')

    def form_valid(self, form):
        nombre = form.cleaned_data["nombre"]
        email = form.cleaned_data["email"]
        comentario = form.cleaned_data["comentario"]
        message_content = (f'{nombre} con email {email} ha escrito lo siguiente: {comentario}')
        success = send_mail(
            ("formulario de contacto de mi web de Instaconquer"),
            message_content,
            "info@angamadev.com",
            ["angamadev@gmail.com"],
            fail_silently=False,
        )
        messages.add_message(self.request,messages.SUCCESS, "Mensaje enviado correctamente")
        return super().form_valid(form)
    
    
class CustomLogoutView(LogoutView):
    next_page = 'login'  # Página a la que redirigir después de cerrar sesión
    success_url = reverse_lazy('home')  # URL a la que redirigir después del inicio de sesión exitoso

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView, ListView,FormView
from .models import UserProfile,Follow
from posts.models import Post
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import ProfileFollow
import ipdb

# Create your views here.
@method_decorator(login_required,name='dispatch')
class ProfileListView(ListView):
    model = UserProfile
    template_name = 'profiles/profile_list.html'
    context_object_name = "profiles"
        
    def get_queryset(self):
        return UserProfile.objects.all().exclude(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class ProfileDetailView(DetailView, FormView):
    model = UserProfile
    template_name = "profiles/profile_detail.html"
    context_object_name = "userprofile"
    form_class = ProfileFollow

    def get_initial(self):
        self.initial['profile_pk'] =  self.get_object().pk
        return super().get_initial()

    def form_valid(self, form):
        profile_pk = form.cleaned_data.get('profile_pk')
        # action = form.cleaned_data.get('action')
        following = UserProfile.objects.get(pk=profile_pk)

        ## Compruebo si lo sigo o no en mi Queryset
        # Si Si lo sigo lo borro de mis seguidores y muestro mensaje
        if Follow.objects.filter(
            follower=self.request.user.profile,
            following=following
            ).count(): 
            Follow.objects.filter(
                follower=self.request.user.profile,
                following=following
                ).delete()
            messages.add_message(
                self.request, 
                messages.SUCCESS, 
                f"Se ha dejado de seguir a {following.user.username}"
                )
        # En cambio si NO lo sigo lo añado a mis seguidores y muestro mensaje
        else:
            Follow.objects.get_or_create(
                follower=self.request.user.profile,
                following=following
                )
            messages.add_message(
                self.request,
                messages.SUCCESS, 
                f"Se empieza a seguir a {following.user.username}"
                )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("profiles:profile_detail", args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        publicaciones = Post.objects.all() 
        context["publicaciones"] = publicaciones

        # Comprobamos si seguimos al usuario
        following = Follow.objects.filter(
            follower=self.request.user.profile, 
            following=self.get_object()
            ).exists()
        context['following'] = following
        return context
    
@method_decorator(login_required,name='dispatch')
class ProfileUpdateView(UpdateView):
    model = UserProfile
    fields = [
        "user",
        "bio",
        "profile_picture",
        "birth_date",        
        ]
    template_name = 'profiles/profile_update.html'
    context_object_name = "profile"
    
    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS,'¡Perfil editado correctamente!')
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse("profiles:profile_detail",args=[self.object.pk])
    
    def dispatch(self, request, *args, **kwargs):
        user_profile = self.get_object()
        if user_profile.user != self.request.user:
            return HttpResponseRedirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

instagram/templates/profiles/profile.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block head_title %}Perfil{% endblock %}
{% block h1_title %}{% trans "Mi Perfil" %}{% endblock %} 
{% block page_content %}
{% load static %}


  <h2> Mi pagina de perfil </h2>
  {% for perfil in perfiles %}
    {% if perfil.user == request.user %}
      <article id="{{ perfil.pk }}">
        <p> Perfil de {{ perfil.user}}</p> 
        <picture>
          <img src="{% thumbnail  perfil.profile_picture 'medium'  %}">
        </picture>
        <p> Biografia: {{ perfil.bio }} </p>
      </article>
      {% endif %}
  {% endfor %}
  {% comment %} <a href={% url "profiles:profile_update" perfil.pk %}><button class="btn btn-info">{% trans "Actualizar" %}</button></a> {% endcomment %}
    <hr>


{% endblock %}

instagram/templates/profiles/profile_detail.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}
{% block h1_title %}{% trans "Usuario logueado " %}{{ request.user.first_name }}{% endblock %} 

{% load static %}
{% block page_content %}
    <div class="container mt-4 ">
        <div class="d-flex justify-content-center">
            {% if userprofile.user != request.user %}
                <h1>{% trans "Detalle de Perfil" %} {{ userprofile.user }}</h1>
            {% else %}
                <h1>{% trans "Mi perfil" %} </h1>
            {% endif %}
        </div>
    </div>
    <div class="container mt-4 mb-5">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="d-flex justify-content-between p-2 px-3">
                        <div class="d-flex flex-row align-items-center"> <img src="{% thumbnail  userprofile.profile_picture 'small'  %}" width="50" class="rounded-circle">
                            <div class="d-flex flex-column ml-5"> 
                                <span class="font-weight-bold ml-5">{{ userprofile.user.first_name }}</span> 
                            </div>
                        </div>
                        <div class="d-flex flex-row mt-1 ellipsis">
                            {% if userprofile.user != request.user %}
                                <form action="" method="post">
                                {% csrf_token %}
                                {{ form.profile_pk|as_crispy_field }}
                                    {% if following %}
                                        <button class="btn btn-info" type="submit">Dejar de seguir</button>
                                    {% else %}
                                        <button class="btn btn-info" type="submit">Seguir</button>
                                    {% endif %}
                                </form>
                            {% endif %}
                            <i class="fa fa-ellipsis-h"></i> 
                        </div>
                    </div>
                    <img src="{% thumbnail  userprofile.profile_picture 'medium'  %}" class="img-fluid">
                    <div class="p-2">
                        <p class="text-justify">{{ userprofile.bio }} </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if following %}
        <div class="container mt-4 ">
            <div class="d-flex justify-content-center">
                <h2> Publicaciones de {{ userprofile.user }} </h2>
            </div>
        </div>
        {% include "posts/post_list.html" %}

    {% else %}
        
        {% if request.user.profile.pk == userprofile.pk %}
            <div class="container mt-4 ">
                <div class="d-flex justify-content-center">
                <button class="btn btn-warning"><a href={% url 'profiles:profile_update' userprofile.pk %}>{% trans "Actualizar" %}</a></button>
                </div>
            </div>
            <div class="container mt-4 ">
                <div class="d-flex justify-content-center">
                    <p> Numero de Seguidores: {{ userprofile.followers.count }}</p>
                </div>
            </div>
            <hr>
            <div class="container mt-4 ">
                <div class="d-flex justify-content-center">
                    <h2> {% trans "Mis publicaciones" %}</h2>
                </div>
            </div>
            {% include "posts/post_list.html" %}
        {% endif %}
    {% endif %}
{% endblock %}

instagram/templates/profiles/profile_list.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block head_title %}Perfil{% endblock %}
{% block h1_title %}INSTACONQUER{% endblock %} 
{% block page_content %}
{% load static %}


  <div class="container">
    <h2>{% trans "Perfiles" %}</h2>
      {% include "_includes/_profiles.html" %}
    <hr>


{% endblock %}

instagram/templates/profiles/profile_update.html
{% extends "general/layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block h1_title %}{% trans "Usuario logueado" %} {{ request.user }}{% endblock %} 


{% block page_content %}
{% load static %}

  <div class="container">
    <h2> {% trans "Modificar Perfil de " %} {{ request.user }}</h2>
      <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-info">{% trans "Actualizar" %}</button>
          {% comment %} <button class="btn btn-danger"><a href={% url 'profiles:profile_detail'  perfil.pk %}>{% trans "Cancelar" %}</a></button> {% endcomment %}
    </form> 
  </div>

{% endblock %}